version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: socialint-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: socialint
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - socialint-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: socialint-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - socialint-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  socialint-network:
    driver: bridge

